In [1]:
import numpy as np

1. , Установите какие произведения матриц A B и B A , определены и
найдите размерности полученных матриц :
а) A — матрица 4 ×2, B — матрица 4 ×2;
б) A — матрица 2×5, B — матрица 5×3;
в) A — матрица 8×3, B — матрица 3×8;
г) A — квадратная матрица 4 ×4, B — квадратная матрица 4 ×4.

Правильно:
Произведением матрицы A=‖ai j‖, имеющей порядки m и n, и матрицы
B=‖bi j‖, включающей порядки n и k, называется матрица C=‖ci j‖ с
порядками m и k:
C=
(
c11 c12 ⋯ c1k
c21 c22 ⋯ c2 k
⋯ ⋯ ⋱ ⋯
cm1
cm2 ⋯ cmk
)
,
наполненная элементами определяемыми формулой , :
ci j=∑
p=1
n
ai p
bp j
.
Матрицу A можно умножить не на любую матрицу B: важно чтобы ,
число столбцов матрицы A было равно числу строк матрицы B.
Проверим это условие на предложенных вариантах :
а) A — матрица 4 ×2, B — матрица 4 ×2; - AB - 2 4, не равно перемножить
нельзя тоже нельзя перемножить так как стобла не равно , BA - , 2( )
количеству строк - 4
б) A — матрица 2×5, B — матрица 5×3; - AB - , перемножить можно
размерность х перемножить нельзя так как не равно 2 3, BA - , 3 2

в) A — матрица 8×3, B — матрица 3×8; - AB , перемножить можно
размерность х перемножить можно размерность х 8 8, BA , 3 3
г) A — квадратная матрица 4 ×4, B — квадратная матрица 4 ×4. - AB, BA -
перемножить можно размерность х , 4 4
2. Найдите сумму и произведение матриц A=(
1 −2
3 0 ) и B=(
4 −1
0 5 )
.
2. Решение
Сумма:
(
1 −2
3 0 )
+(
4 −1
0 5 )=(
5 −3
3 5 )

In [3]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a + b


array([[ 5, -3],
       [ 3,  5]])

In [4]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

In [5]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3 * a + (-2) * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

. Дана матрица A=(
4 1
5 −2
2 3 )
. Вычислите A A
T
 и A
T
A.

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [7]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [8]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

### Практическое задание. Часть 2

In [9]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(b)

180.0

In [10]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(c), 2)

0.0

2. Определитель матрицы A равен 4. : Найдите
а) d e t ( A
2
);
б) d e t ( A
T
);
в) d e t (2 A).

In [11]:
c = np.array([[-2, 7, -3], [4, -14, 6],[-3, 7, 13]])
np.linalg.det(c)

0.0

In [12]:
a = np.array([[1, 2, 3], [1, 1, 1],[2, 3, 4]])
np.linalg.matrix_rank(a)

2